server:
  servlet:
    context-path: /app
  port: 8189
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file:.\Database.db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect

